apiVersion: v1
kind: Pod
metadata: 
name: meme-app
labels:
    app: k8s-memes
spec:
containers:
- name: k8s-meme-app
    image: pavangudiwada/dockerimage:v1
    ports:
    - containerPort: 5000
        protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
